on:
  push:
    branches:
      - main
  pull_request: ~

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        include:
          - php: '8.1'
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: date.timezone=Europe/Riga,memory_limit=-1
          php-version: "${{ matrix.php }}"
          tools: composer,flex

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"


      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-


      - name: Install dependencies
        run: composer install

      - name: Run PhpUnit
        run: ./bin/phpunit

      - name: Running Code Style Check
        run: ./bin/php-cs-fixer fix -v --diff --dry-run
